# Generated by Django 4.2.11 on 2025-11-02 04:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique zone code (e.g., ZN001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "boundary",
                    models.JSONField(
                        blank=True,
                        help_text="Zone geographical boundary (GeoJSON)",
                        null=True,
                    ),
                ),
                (
                    "center_point_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "center_point_lon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "speed_limit",
                    models.IntegerField(
                        help_text="Speed limit in km/h",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="devices_zon_code_729a87_idx"),
                    models.Index(
                        fields=["is_active"], name="devices_zon_is_acti_e5a7fc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Device identifier (e.g., CAM001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("camera", "Traffic Camera"),
                            ("sensor", "Traffic Sensor"),
                            ("radar", "Speed Radar"),
                        ],
                        default="camera",
                        max_length=20,
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Device GPS Latitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "location_lon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Device GPS Longitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("rtsp_url", models.URLField(help_text="RTSP stream URL")),
                ("rtsp_username", models.CharField(blank=True, max_length=50)),
                ("rtsp_password", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("resolution", models.CharField(default="1920x1080", max_length=20)),
                (
                    "fps",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "calibration_matrix",
                    models.JSONField(
                        blank=True, help_text="Camera calibration data", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="devices.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DeviceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("online", "Device Online"),
                            ("offline", "Device Offline"),
                            ("error", "Device Error"),
                            ("maintenance", "Maintenance Mode"),
                            ("calibration", "Calibration Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="devices_dev_device__5b0de9_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="devices_dev_event_t_6d20f2_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["code"], name="devices_dev_code_767230_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["zone"], name="devices_dev_zone_id_926c7c_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="devices_dev_status_bbf58f_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_type"], name="devices_dev_device__0d8d82_idx"
            ),
        ),
    ]
