# Generated by Django 5.2.7 on 2025-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rtsp_url',
            field=models.CharField(
                help_text='RTSP stream URL (supports rtsp://user:pass@ip:port/stream format)',
                max_length=255
            ),
        ),
    ]
