# Generated by Django 4.2.11 on 2025-11-02 04:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("dni", "DNI"),
                            ("passport", "Passport"),
                            ("foreign_card", "Foreign Card"),
                        ],
                        default="dni",
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("license_number", models.CharField(blank=True, max_length=20)),
                ("license_class", models.CharField(blank=True, max_length=10)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("is_suspended", models.BooleanField(default=False)),
                ("suspension_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        help_text="License plate in Peru format (e.g., ABC-123, AB-1234)",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid license plate format. Use AAA-123, AB-1234, or A12-345 format.",
                                regex="^[A-Z]{3}-\\d{3,4}$|^[A-Z]{2}-\\d{4}$|^[A-Z]\\d{2}-\\d{3}$",
                            )
                        ],
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=50)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=30)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "Automobile"),
                            ("truck", "Truck"),
                            ("bus", "Bus"),
                            ("motorcycle", "Motorcycle"),
                            ("bicycle", "Bicycle"),
                            ("other", "Other"),
                        ],
                        default="car",
                        max_length=20,
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("owner_dni", models.CharField(blank=True, max_length=20)),
                ("owner_address", models.TextField(blank=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("is_stolen", models.BooleanField(default=False)),
                ("is_wanted", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("sunarp_last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["license_plate"],
            },
        ),
        migrations.CreateModel(
            name="VehicleOwnership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_primary_owner", models.BooleanField(default=True)),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="vehicles.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["license_plate"], name="vehicles_ve_license_907c55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["owner_dni"], name="vehicles_ve_owner_d_b3eb80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["is_stolen"], name="vehicles_ve_is_stol_f22ded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["is_wanted"], name="vehicles_ve_is_want_b9a47b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["document_number"], name="vehicles_dr_documen_45aca3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["license_number"], name="vehicles_dr_license_de2c16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["is_suspended"], name="vehicles_dr_is_susp_92ae1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleownership",
            index=models.Index(
                fields=["vehicle"], name="vehicles_ve_vehicle_a3bb7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleownership",
            index=models.Index(
                fields=["driver"], name="vehicles_ve_driver__d1090b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleownership",
            index=models.Index(
                fields=["is_primary_owner"], name="vehicles_ve_is_prim_afe9c0_idx"
            ),
        ),
    ]
