# Generated by Django 4.2.11 on 2025-11-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="risk_category",
            field=models.CharField(
                choices=[
                    ("low", "Low Risk"),
                    ("medium", "Medium Risk"),
                    ("high", "High Risk"),
                    ("critical", "Critical Risk"),
                ],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="risk_score",
            field=models.FloatField(
                default=0.0, help_text="ML-calculated risk score (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="risk_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
