# Generated by Django 4.2.11 on 2025-11-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0002_driver_risk_category_driver_risk_score_and_more"),
        (
            "infractions",
            "0003_infraction_accident_risk_infraction_recidivism_risk_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name (e.g., 'recidivism_xgboost', 'accident_lstm')",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Model version (e.g., 'v1.2.3', '2025-11-01')",
                        max_length=50,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("classification", "Classification"),
                            ("regression", "Regression"),
                            ("clustering", "Clustering"),
                            ("detection", "Object Detection"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("xgboost", "XGBoost"),
                            ("sklearn", "Scikit-Learn"),
                            ("tensorflow", "TensorFlow"),
                            ("pytorch", "PyTorch"),
                            ("lightgbm", "LightGBM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("framework_version", models.CharField(blank=True, max_length=50)),
                (
                    "model_path",
                    models.TextField(
                        help_text="Path to model file (e.g., 's3://models/recidivism_v1.2.3.pkl')"
                    ),
                ),
                ("model_size_mb", models.FloatField(blank=True, null=True)),
                ("mlflow_run_id", models.CharField(blank=True, max_length=100)),
                ("mlflow_experiment_id", models.CharField(blank=True, max_length=100)),
                ("mlflow_model_uri", models.TextField(blank=True)),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Model metrics (accuracy, precision, recall, f1_score, auc_roc, etc.)",
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(default=dict, help_text="Model hyperparameters"),
                ),
                ("training_dataset_path", models.TextField(blank=True)),
                ("training_dataset_size", models.IntegerField(blank=True, null=True)),
                ("validation_dataset_path", models.TextField(blank=True)),
                ("test_dataset_path", models.TextField(blank=True)),
                (
                    "feature_names",
                    models.JSONField(default=list, help_text="List of feature names"),
                ),
                (
                    "feature_importance",
                    models.JSONField(
                        default=dict, help_text="Feature importance scores"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Is this model currently active/deployed?",
                    ),
                ),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deployment_environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        default="development",
                        max_length=50,
                    ),
                ),
                ("prediction_count", models.BigIntegerField(default=0)),
                ("avg_prediction_time_ms", models.FloatField(blank=True, null=True)),
                ("last_prediction_at", models.DateTimeField(blank=True, null=True)),
                ("data_drift_detected", models.BooleanField(default=False)),
                ("concept_drift_detected", models.BooleanField(default=False)),
                ("drift_check_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ml_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployed_ml_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLPrediction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("recidivism", "Recidivism Risk"),
                            ("accident_risk", "Accident Risk"),
                            ("severity", "Infraction Severity"),
                            ("driver_risk", "Driver Risk Score"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "prediction_value",
                    models.FloatField(
                        help_text="Predicted value (probability for classification, value for regression)"
                    ),
                ),
                (
                    "prediction_class",
                    models.CharField(
                        blank=True,
                        help_text="Predicted class for classification (e.g., 'high', 'medium', 'low')",
                        max_length=50,
                    ),
                ),
                (
                    "prediction_confidence",
                    models.FloatField(
                        blank=True, help_text="Confidence score 0-1", null=True
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        help_text="Feature values used for this prediction"
                    ),
                ),
                (
                    "actual_value",
                    models.FloatField(
                        blank=True,
                        help_text="Actual outcome (filled in later for model evaluation)",
                        null=True,
                    ),
                ),
                ("actual_class", models.CharField(blank=True, max_length=50)),
                (
                    "prediction_time_ms",
                    models.FloatField(
                        blank=True, help_text="Time taken to make prediction", null=True
                    ),
                ),
                (
                    "predicted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_predictions",
                        to="vehicles.driver",
                    ),
                ),
                (
                    "infraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_predictions",
                        to="infractions.infraction",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="ml_models.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-predicted_at"],
                "indexes": [
                    models.Index(
                        fields=["model", "-predicted_at"],
                        name="ml_models_m_model_i_23f478_idx",
                    ),
                    models.Index(
                        fields=["infraction"], name="ml_models_m_infract_ed1726_idx"
                    ),
                    models.Index(
                        fields=["driver", "-predicted_at"],
                        name="ml_models_m_driver__5f0e92_idx",
                    ),
                    models.Index(
                        fields=["prediction_type", "-predicted_at"],
                        name="ml_models_m_predict_472780_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["model_name", "version"], name="ml_models_m_model_n_f508f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["is_active"], name="ml_models_m_is_acti_afbf29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["deployment_environment"], name="ml_models_m_deploym_14de3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["-last_prediction_at"], name="ml_models_m_last_pr_205647_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mlmodel",
            unique_together={("model_name", "version")},
        ),
    ]
