# Generated by Django 4.2.11 on 2025-11-02 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Infraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "infraction_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "infraction_type",
                    models.CharField(
                        choices=[
                            ("speed", "Speed Violation"),
                            ("red_light", "Red Light Violation"),
                            ("wrong_lane", "Wrong Lane Usage"),
                            ("no_helmet", "No Helmet"),
                            ("parking", "Illegal Parking"),
                            ("phone_use", "Phone Use While Driving"),
                            ("seatbelt", "No Seatbelt"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Infraction GPS Latitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "location_lon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Infraction GPS Longitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("license_plate_detected", models.CharField(blank=True, max_length=10)),
                (
                    "license_plate_confidence",
                    models.FloatField(
                        default=0.0, help_text="OCR confidence score 0-1"
                    ),
                ),
                (
                    "detected_speed",
                    models.FloatField(blank=True, help_text="Speed in km/h", null=True),
                ),
                (
                    "speed_limit",
                    models.IntegerField(
                        blank=True, help_text="Speed limit at location", null=True
                    ),
                ),
                (
                    "snapshot_url",
                    models.URLField(blank=True, help_text="URL to snapshot image"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="URL to video evidence"),
                ),
                (
                    "evidence_metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional evidence data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("validated", "Validated"),
                            ("rejected", "Rejected"),
                            ("appealed", "Under Appeal"),
                            ("paid", "Fine Paid"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "fine_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fine_due_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, help_text="When the infraction was detected"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infractions",
                        to="devices.device",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infractions",
                        to="vehicles.driver",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_infractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infractions",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infractions",
                        to="devices.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for appeal")),
                ("evidence_description", models.TextField(blank=True)),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True, default=list, help_text="List of document URLs"
                    ),
                ),
                ("appellant_name", models.CharField(max_length=200)),
                ("appellant_dni", models.CharField(max_length=20)),
                ("appellant_phone", models.CharField(blank=True, max_length=20)),
                ("appellant_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("review_decision", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "infraction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeal",
                        to="infractions.infraction",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="InfractionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("detected", "Infraction Detected"),
                            ("reviewed", "Manual Review"),
                            ("validated", "Validated"),
                            ("rejected", "Rejected"),
                            ("appealed", "Appeal Filed"),
                            ("payment_received", "Payment Received"),
                            ("dismissed", "Dismissed"),
                            ("notice_sent", "Notice Sent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "infraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="infractions.infraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["infraction", "-timestamp"],
                        name="infractions_infract_089142_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="infractions_event_t_728a74_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="infraction",
            index=models.Index(
                fields=["infraction_code"], name="infractions_infract_83f8da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infraction",
            index=models.Index(
                fields=["device", "-detected_at"], name="infractions_device__696240_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infraction",
            index=models.Index(
                fields=["zone", "-detected_at"], name="infractions_zone_id_4187a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infraction",
            index=models.Index(
                fields=["infraction_type", "-detected_at"],
                name="infractions_infract_ee0e51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="infraction",
            index=models.Index(fields=["status"], name="infractions_status_f3736a_idx"),
        ),
        migrations.AddIndex(
            model_name="infraction",
            index=models.Index(
                fields=["license_plate_detected"], name="infractions_license_cd67b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infraction",
            index=models.Index(
                fields=["vehicle"], name="infractions_vehicle_dbbc65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(
                fields=["infraction"], name="infractions_infract_679c79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(fields=["status"], name="infractions_status_325877_idx"),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(
                fields=["appellant_dni"], name="infractions_appella_1bcf2c_idx"
            ),
        ),
    ]
