# Generated by Django 4.2.11 on 2025-11-03 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("vehicles", "0001_initial"),
        ("infractions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("truck", "Truck"),
                            ("bus", "Bus"),
                            ("motorcycle", "Motorcycle"),
                            ("bicycle", "Bicycle"),
                            ("person", "Person"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Detection confidence score 0-1"),
                ),
                ("license_plate_detected", models.CharField(blank=True, max_length=10)),
                (
                    "license_plate_confidence",
                    models.FloatField(
                        default=0.0, help_text="OCR confidence score 0-1"
                    ),
                ),
                (
                    "bbox_x1",
                    models.FloatField(help_text="Top-left X coordinate (normalized)"),
                ),
                (
                    "bbox_y1",
                    models.FloatField(help_text="Top-left Y coordinate (normalized)"),
                ),
                (
                    "bbox_x2",
                    models.FloatField(
                        help_text="Bottom-right X coordinate (normalized)"
                    ),
                ),
                (
                    "bbox_y2",
                    models.FloatField(
                        help_text="Bottom-right Y coordinate (normalized)"
                    ),
                ),
                (
                    "estimated_speed",
                    models.FloatField(blank=True, help_text="Speed in km/h", null=True),
                ),
                (
                    "has_infraction",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this detection has an associated infraction",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional detection data"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="camera",
                        help_text="Detection source (camera, webcam_local, etc)",
                        max_length=50,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, help_text="When the detection occurred"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="devices.device",
                    ),
                ),
                (
                    "infraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_detection",
                        to="infractions.infraction",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detections",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="devices.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Detection",
                "verbose_name_plural": "Vehicle Detections",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-detected_at"],
                        name="infractions_device__b22ab8_idx",
                    ),
                    models.Index(
                        fields=["vehicle_type", "-detected_at"],
                        name="infractions_vehicle_bb01cf_idx",
                    ),
                    models.Index(
                        fields=["has_infraction"], name="infractions_has_inf_2b770c_idx"
                    ),
                    models.Index(
                        fields=["source", "-detected_at"],
                        name="infractions_source_035e58_idx",
                    ),
                    models.Index(
                        fields=["license_plate_detected"],
                        name="infractions_license_4e6e5c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DetectionStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField(db_index=True)),
                ("period_end", models.DateTimeField()),
                ("car_count", models.IntegerField(default=0)),
                ("truck_count", models.IntegerField(default=0)),
                ("bus_count", models.IntegerField(default=0)),
                ("motorcycle_count", models.IntegerField(default=0)),
                ("bicycle_count", models.IntegerField(default=0)),
                ("person_count", models.IntegerField(default=0)),
                ("other_count", models.IntegerField(default=0)),
                ("total_detections", models.IntegerField(default=0)),
                (
                    "total_with_plate",
                    models.IntegerField(
                        default=0, help_text="Detections with license plate identified"
                    ),
                ),
                ("total_infractions", models.IntegerField(default=0)),
                ("avg_confidence", models.FloatField(default=0.0)),
                (
                    "avg_speed",
                    models.FloatField(
                        blank=True, help_text="Average speed in km/h", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_stats",
                        to="devices.device",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_stats",
                        to="devices.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection Statistics",
                "verbose_name_plural": "Detection Statistics",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["period_type", "-period_start"],
                        name="infractions_period__e5d1df_idx",
                    ),
                    models.Index(
                        fields=["device", "-period_start"],
                        name="infractions_device__fe5c84_idx",
                    ),
                    models.Index(
                        fields=["zone", "-period_start"],
                        name="infractions_zone_id_e4f2de_idx",
                    ),
                ],
                "unique_together": {("period_type", "period_start", "device", "zone")},
            },
        ),
    ]
