# Generated by Django 4.2.11 on 2025-11-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infractions", "0002_vehicledetection_detectionstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="infraction",
            name="accident_risk",
            field=models.FloatField(
                blank=True, help_text="Predicted accident risk (0-1)", null=True
            ),
        ),
        migrations.AddField(
            model_name="infraction",
            name="recidivism_risk",
            field=models.FloatField(
                blank=True,
                help_text="Predicted recidivism probability (0-1)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="infraction",
            name="risk_factors",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Top risk factors with importance scores",
            ),
        ),
    ]
